# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgrasplabel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ForGraspLabel(object):
    def setupUi(self, ForGraspLabel):
        ForGraspLabel.setObjectName("ForGraspLabel")
        ForGraspLabel.resize(1214, 910)
        self.centralwidget = QtWidgets.QWidget(ForGraspLabel)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphWidget = QtWidgets.QWidget(self.widget_2)
        self.graphWidget.setObjectName("graphWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.graphWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graphWindow = QtWidgets.QLabel(self.graphWidget)
        self.graphWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.graphWindow.setStyleSheet("border:1px solid rgb(0,0,0);background-color: white")
        self.graphWindow.setText("")
        self.graphWindow.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.graphWindow.setObjectName("graphWindow")
        self.horizontalLayout_5.addWidget(self.graphWindow)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.addWidget(self.graphWidget)
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.axisLabel = QtWidgets.QLabel(self.widget_2)
        self.axisLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.axisLabel.setObjectName("axisLabel")
        self.horizontalLayout_7.addWidget(self.axisLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.classList = QtWidgets.QListWidget(self.widget_2)
        self.classList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.classList.setFlow(QtWidgets.QListView.LeftToRight)
        self.classList.setObjectName("classList")
        self.verticalLayout_5.addWidget(self.classList)
        self.verticalLayout_5.setStretch(0, 9)
        self.verticalLayout_5.setStretch(3, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.stepNum = QtWidgets.QLineEdit(self.widget)
        self.stepNum.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.stepNum.setObjectName("stepNum")
        self.horizontalLayout_2.addWidget(self.stepNum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lastButton = QtWidgets.QPushButton(self.widget_3)
        self.lastButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lastButton.setObjectName("lastButton")
        self.gridLayout_2.addWidget(self.lastButton, 0, 0, 1, 1)
        self.nextButton = QtWidgets.QPushButton(self.widget_3)
        self.nextButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout_2.addWidget(self.nextButton, 0, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.widget_3)
        self.saveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.saveButton, 1, 0, 1, 1)
        self.autosaveCheck = QtWidgets.QCheckBox(self.widget_3)
        self.autosaveCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.autosaveCheck.setChecked(True)
        self.autosaveCheck.setObjectName("autosaveCheck")
        self.gridLayout_2.addWidget(self.autosaveCheck, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.scollSpeedSlider = QtWidgets.QSlider(self.widget_8)
        self.scollSpeedSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scollSpeedSlider.setMinimum(1)
        self.scollSpeedSlider.setMaximum(100)
        self.scollSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scollSpeedSlider.setObjectName("scollSpeedSlider")
        self.horizontalLayout_3.addWidget(self.scollSpeedSlider)
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.jawWidthInput = QtWidgets.QLineEdit(self.widget_7)
        self.jawWidthInput.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.jawWidthInput.setObjectName("jawWidthInput")
        self.horizontalLayout_4.addWidget(self.jawWidthInput)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.originWidthCheck = QtWidgets.QCheckBox(self.widget_6)
        self.originWidthCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.originWidthCheck.setChecked(True)
        self.originWidthCheck.setObjectName("originWidthCheck")
        self.verticalLayout_2.addWidget(self.originWidthCheck)
        self.widget_9 = QtWidgets.QWidget(self.widget_6)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.simpleWidthRadio = QtWidgets.QRadioButton(self.widget_9)
        self.simpleWidthRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.simpleWidthRadio.setChecked(False)
        self.simpleWidthRadio.setObjectName("simpleWidthRadio")
        self.horizontalLayout_6.addWidget(self.simpleWidthRadio)
        self.complexWidthRadio = QtWidgets.QRadioButton(self.widget_9)
        self.complexWidthRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.complexWidthRadio.setChecked(True)
        self.complexWidthRadio.setObjectName("complexWidthRadio")
        self.horizontalLayout_6.addWidget(self.complexWidthRadio)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.redoButton = QtWidgets.QPushButton(self.widget_4)
        self.redoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.redoButton.setObjectName("redoButton")
        self.gridLayout.addWidget(self.redoButton, 0, 1, 1, 1)
        self.undoButton = QtWidgets.QPushButton(self.widget_4)
        self.undoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.undoButton.setObjectName("undoButton")
        self.gridLayout.addWidget(self.undoButton, 0, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.widget_4)
        self.clearButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 1, 1, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.widget_4)
        self.deleteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.labelList = QtWidgets.QListWidget(self.widget_5)
        self.labelList.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelList.setObjectName("labelList")
        self.verticalLayout_4.addWidget(self.labelList)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(5, 1)
        self.verticalLayout_3.setStretch(7, 8)
        self.horizontalLayout.addWidget(self.widget)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        ForGraspLabel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ForGraspLabel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1214, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuview = QtWidgets.QMenu(self.menubar)
        self.menuview.setObjectName("menuview")
        ForGraspLabel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ForGraspLabel)
        self.statusbar.setObjectName("statusbar")
        ForGraspLabel.setStatusBar(self.statusbar)
        self.actionDataset_Path = QtWidgets.QAction(ForGraspLabel)
        self.actionDataset_Path.setObjectName("actionDataset_Path")
        self.actionLabel_Path = QtWidgets.QAction(ForGraspLabel)
        self.actionLabel_Path.setObjectName("actionLabel_Path")
        self.actionClass_File = QtWidgets.QAction(ForGraspLabel)
        self.actionClass_File.setObjectName("actionClass_File")
        self.actionBoth_Path = QtWidgets.QAction(ForGraspLabel)
        self.actionBoth_Path.setObjectName("actionBoth_Path")
        self.actionAutoResize = QtWidgets.QAction(ForGraspLabel)
        self.actionAutoResize.setObjectName("actionAutoResize")
        self.menuFile.addAction(self.actionDataset_Path)
        self.menuFile.addAction(self.actionLabel_Path)
        self.menuFile.addAction(self.actionBoth_Path)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClass_File)
        self.menuFile.addSeparator()
        self.menuview.addAction(self.actionAutoResize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuview.menuAction())

        self.retranslateUi(ForGraspLabel)
        QtCore.QMetaObject.connectSlotsByName(ForGraspLabel)

    def retranslateUi(self, ForGraspLabel):
        _translate = QtCore.QCoreApplication.translate
        ForGraspLabel.setWindowTitle(_translate("ForGraspLabel", "GPM - Grasp Path Marker"))
        self.label_3.setText(_translate("ForGraspLabel", "Classes:"))
        self.axisLabel.setText(_translate("ForGraspLabel", "()"))
        self.label_2.setText(_translate("ForGraspLabel", "    No:"))
        self.lastButton.setText(_translate("ForGraspLabel", "last"))
        self.lastButton.setShortcut(_translate("ForGraspLabel", "["))
        self.nextButton.setText(_translate("ForGraspLabel", "next"))
        self.nextButton.setShortcut(_translate("ForGraspLabel", "]"))
        self.saveButton.setText(_translate("ForGraspLabel", "Save"))
        self.saveButton.setShortcut(_translate("ForGraspLabel", "Ctrl+S"))
        self.autosaveCheck.setText(_translate("ForGraspLabel", "Autosave"))
        self.autosaveCheck.setShortcut(_translate("ForGraspLabel", "Ctrl+Shift+S"))
        self.label_5.setText(_translate("ForGraspLabel", "Scoll Speed"))
        self.label_4.setText(_translate("ForGraspLabel", "Jaw Width"))
        self.jawWidthInput.setText(_translate("ForGraspLabel", "30"))
        self.originWidthCheck.setText(_translate("ForGraspLabel", "Save Origin Object Width"))
        self.simpleWidthRadio.setText(_translate("ForGraspLabel", "Width"))
        self.complexWidthRadio.setText(_translate("ForGraspLabel", "Width(array)"))
        self.redoButton.setText(_translate("ForGraspLabel", "Redo"))
        self.redoButton.setShortcut(_translate("ForGraspLabel", "Ctrl+Y"))
        self.undoButton.setText(_translate("ForGraspLabel", "Undo"))
        self.undoButton.setShortcut(_translate("ForGraspLabel", "Ctrl+Z"))
        self.clearButton.setText(_translate("ForGraspLabel", "Clear"))
        self.clearButton.setShortcut(_translate("ForGraspLabel", "Ctrl+C"))
        self.deleteButton.setText(_translate("ForGraspLabel", "Delete"))
        self.deleteButton.setShortcut(_translate("ForGraspLabel", "Ctrl+D"))
        self.label.setText(_translate("ForGraspLabel", "Grasp labels:"))
        self.menuFile.setTitle(_translate("ForGraspLabel", "File"))
        self.menuview.setTitle(_translate("ForGraspLabel", "view"))
        self.actionDataset_Path.setText(_translate("ForGraspLabel", "Dataset Path"))
        self.actionDataset_Path.setShortcut(_translate("ForGraspLabel", "Ctrl+O"))
        self.actionLabel_Path.setText(_translate("ForGraspLabel", "Label Path"))
        self.actionLabel_Path.setShortcut(_translate("ForGraspLabel", "Ctrl+Alt+O"))
        self.actionClass_File.setText(_translate("ForGraspLabel", "Class File"))
        self.actionClass_File.setShortcut(_translate("ForGraspLabel", "Ctrl+G"))
        self.actionBoth_Path.setText(_translate("ForGraspLabel", "Both Path"))
        self.actionBoth_Path.setShortcut(_translate("ForGraspLabel", "Ctrl+Shift+O"))
        self.actionAutoResize.setText(_translate("ForGraspLabel", "Auto Resize"))
        self.actionAutoResize.setShortcut(_translate("ForGraspLabel", "Ctrl+R"))

